<?php
require("Animal.php");
require("Voiture.php");
echo Animal::MAMMIFERE;

// $animal = new Animal();
// echo '<br>';
Animal::afficheAnimal();
echo '<br>';
echo Animal::getNom();
echo '<br>';
echo Animal::setNom('fifou');
echo '<br>';
echo Voiture::getMarque();
echo '<br>';
echo Voiture::getCouleur();
echo '<br>';
echo Voiture::getDistance();
echo '<br>';
echo Voiture::getTemps();
echo '<br>';
echo Voiture::getMarque();
echo '<br>';
echo Voiture::afficheVitesse();
echo '<br>';
echo Voiture::afficheDistance();
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
